<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{orgclockr}
-->
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#sec-1">1. Introduction to orgclockr</a></li>
</ul>
</div>
</div>

# Introduction to orgclockr<a id="sec-1"></a>

Corresponding to its description, the Emacs-mode [Org mode](http://orgmode.org/manual/index.html#Top) is an organizational tool that lives in the plain text world. Furthermore, it's a quite complex markup language. Complexity is not imposed though, jumping into it is adviced here. What sets Org mode apart other organizational tools is the seemingly flawless integration of a full-fledged task management solution into a flexible outliner.

There are [various parsers](http://orgmode.org/worg/org-tools/) for elements in org files, even one in R ([orgR](http://cran.r-project.org/web/packages/orgR/index.html)) is available on CRAN. I recommend using orgR for quickly extracting the raw headings and timestamps of an org file, but the results on todo keywords and tags were certainly not satisfactory. `orgclockr` strives to provide more flexible extraction functions for the elements of org headings.

Org mode allows to clock the time spent on a task. The relevant information is stored in timestamps in a drawer. Furthermore, to fix a time limit, Org mode uses an effort property. These elements will be parsed by `orgclockr` and the time spent, the period of time on a task and the effort set returned per task. These informations allow for a more detailed clock report than the built-in `org-clock-report` in Org mode.